#!/usr/bin/env python3
"""
Snapmaker U1/J1 - GUI Italian Patcher v1.1
Traduci l'interfaccia della tua stampante in Italiano in modo sicuro!
"""
import sys, os

print("==========================================")
print("  Snapmaker Italian GUI Patch - Mod v1.1  ")
print("==========================================\n")

SRC  = '/usr/bin/gui'
BAK  = '/usr/bin/gui.bak'
DST  = '/tmp/gui_patched'

# IL TUO DIZIONARIO COMPLETO
TRANSLATIONS = {
    'версия': "versione",
    'Must home Z axis first:': "Azzerare prima l'asse Z:",
    'ru-RU': 'it-IT',
    'Русский': 'Italiano',
    'Отмена': 'Annulla',
    'Подтвердить': 'Conferma',
    'Понятно': 'Capito',
    'Завершено': 'Completato',
    'Успешно': 'Successo',
    'Неудачно': 'Fallito',
    'Готово': 'Fatto',
    'Позже': 'Dopo',
    'Открыть': 'Apri',
    'Закрыть': 'Chiudi',
    'Продолжить': 'Continua',
    'Исправить сейчас': 'Correggi ora',
    'Отправить': 'Invia',
    'Осталось': 'Rimanente',
    'Общий': 'Generale',
    'Начать': 'Inizia',
    'Далее': 'Avanti',
    'Удалить': 'Elimina',
    'Домой': 'Home',
    'Домой...': 'Home...',
    'Пропустить': 'Salta',
    'Локально': 'Locale',
    'Экспорт': 'Esporta',
    'Взять': 'Prendi',
    'Сохранить': 'Salva',
    'Сохранено': 'Salvato',
    'Возобновить': 'Riprendi',
    'Повторить попытку': 'Riprova',
    'Согласиться': 'Accetto',
    'Выйти': 'Esci',
    'Обнаружить': 'Rileva',
    'Сканировать': 'Scansiona',
    'Очистить': 'Pulisci',
    'Редактировать сейчас': 'Modifica ora',
    'Настройте позже': 'Configura dopo',
    'Подключить сеть': 'Connetti rete',
    'Подключиться сейчас': 'Connetti ora',
    'Давайте создадим что-нибудь чудесное.': 'Creiamo qualcosa di meraviglioso.',
    'Вы уверены, что хотите остановить печать?': 'Vuoi davvero fermare la stampa?',
    'Восстановление печати, Питание принтера было отключено во время печати. Хотите возобновить печать?': 'Mancanza di corrente rilevata durante la stampa. Riprendere?',
    'Печать': 'Stampa',
    'Печать модели': 'Stampa modello',
    'Выбор файла': 'Scegli file',
    'Настройка цветов': 'Imposta colori',
    'Начало печати': 'Inizio stampa',
    'Перепечатка': 'Ristampa',
    'Печать отменена': 'Stampa annullata',
    'Запрещено во время печати': 'Vietato durante la stampa',
    'Загрузка файла для печати...': 'Caricamento file di stampa...',
    'Распаковка файлов...': 'Estrazione file...',
    'Настройки печати': 'Impostazioni stampa',
    'Возобновление печати...': 'Ripresa stampa...',
    'Расширенные параметры': 'Parametri avanzati',
    'Скорость печати': "Velocità di stampa",
    'Пропуск деталей': 'Salta oggetti',
    'Удалить выбранные файлы?': 'Eliminare i file selezionati?',
    'Экспортировать выбранные файлы?': 'Esportare i file selezionati?',
    'Пожалуйста, выберите файл для удаления.': 'Seleziona un file da eliminare.',
    'Местный экспорт': 'Esporta locale',
    'Локальное удаление': 'Elimina locale',
    'Ваш принтер готов. Давайте распечатаем вашу первую модель!': 'Stampante pronta. Stampiamo il primo modello!',
    'Для повторной печати будут использоваться та же самая печатающая головка и тот же филамент.': 'Verranno usate la stessa testina e lo stesso filamento.',
    'Вы уверены, что хотите пропустить этот объект?': 'Vuoi davvero saltare questo oggetto?',
    'Съемка таймлапс': 'Timelapse',
    'Недостаточно места для запуска съемки таймлапс. Пожалуйста, освободите место и попробуйте снова.': 'Spazio esaurito per timelapse. Libera spazio e riprova.',
    'Видеоролики с тайм-лапс отсутствуют.': 'Nessun video time-lapse.',
    'Экспорт тайм-лапс съемки': 'Esporta time-lapse',
    'Удалить тайм-лапс съемку': 'Elimina time-lapse',
    'Динамическая калибровка потока': 'Calibrazione dinamica flusso',
    'Калибровка экструзионного потока': 'Calibrazione flusso estrusione',
    'Выберите печатную головку': 'Seleziona testina',
    'Скорость вентилятора': "Velocità ventola",
    'Ошибка запуска Klipper': 'Errore avvio Klipper',
    'Обнаружение стола\u2026': 'Rilevamento piano...',
    'Файлы Gcode отсутствуют': 'Nessun file Gcode trovato',
    'Нераспознанный тип G-кода': 'Tipo G-code non riconosciuto',
    'Нераспознанный тип G-кода. Продолжение печати может привести к сбою или повреждению принтера. Вы хотите продолжить?': 'G-code non riconosciuto. Continuare potrebbe causare errori o danni. Continuare?',
    'Сканирование файла Gcode...': 'Scansione file Gcode...',
    'Текущая температура печатающей головки установлена \u200b\u200bна 0 градусов Цельсия. Продолжение печати может привести к сбою. Продолжить?': 'Temp. testina a 0 gradi C. Continuare potrebbe causare errori. Continuare?',
    'Возврат по осям X и Y в исходное положение\u2026': 'Homing assi X e Y...',
    'Хотите удалить все файлы Gcode и файлы таймлапса?': 'Eliminare tutti i file Gcode e timelapse?',
    'Сначала вставьте USB-флешку.': 'Inserire prima la chiavetta USB.',
    'Печатающие головки': 'Testine di stampa',
    'Печатающая головка': 'Testina di stampa',
    'Печатающая головка 1': 'Testina 1',
    'Печатающая головка 2': 'Testina 2',
    'Печатающая головка 3': 'Testina 3',
    'Печатающая головка 4': 'Testina 4',
    'Сопло': 'Ugello',
    'сопло': 'ugello',
    'Экструдер': 'Estrusore',
    'РЕТРАКТ': 'RITRAI',
    'ЭКСТРУЗИЯ': 'ESTRUDI',
    'Загрузка...': 'Caricamento...',
    'Прикрепить печатающую головку': 'Aggancia testina',
    'Отсоедините печатающую головку': 'Sgancia testina',
    'Информация о печатающей головке': 'Info testina',
    'Диаметр сопла': 'Diametro ugello',
    'Диаметр сопла: Печатающая головка 1': 'Diametro ugello: Testina 1',
    'Диаметр сопла: Печатающая головка 2': 'Diametro ugello: Testina 2',
    'Диаметр сопла: Печатающая головка 3': 'Diametro ugello: Testina 3',
    'Диаметр сопла: Печатающая головка 4': 'Diametro ugello: Testina 4',
    'Примерное оставшееся время': 'Tempo rimanente stimato',
    'Температура сопла': 'Temperatura ugello',
    'Выберите печатающую головку(и) для калибровки.': 'Seleziona testina/e per la calibrazione.',
    'Выберите как минимум одну печатающую головку для калибровки.': 'Seleziona almeno una testina per la calibrazione.',
    'Пожалуйста, выберите печатающую головку, из которой вы хотите удалить материал после печати.': 'Seleziona la testina da cui rimuovere il materiale a fine stampa.',
    'Пожалуйста, выберите хотя бы одну печатающую головку для возврата материала.': 'Seleziona almeno una testina per la retrazione.',
    'Установка печатающей головки': 'Installazione testina',
    'Отсоединение печатающей головки': 'Smontaggio testina',
    'Калибровка печатающей головки': 'Calibrazione testina',
    'Ошибка установки и возврата печатающей головки': 'Errore installazione e ritorno testina',
    'Исключение при возврате в исходное положение': 'Eccezione ritorno posizione',
    'Проверка крепления и отсоединения печатающей головки...': 'Verifica montaggio e smontaggio testina...',
    'Контроль': 'Controllo',
    'Движение': 'Movimento',
    'Температура': 'Temperatura',
    'Температура нагреваемой платформы': 'Temperatura piano riscaldato',
    'Светодиодная лента': 'Striscia LED',
    'Очиститель': 'Purificatore',
    'Скорость вращения основного вентилятора охлаждения': 'Velocità ventola di raffreddamento principale',
    'Скорость вращения вентилятора системы охлаждения': 'Velocità ventola di raffreddamento ausiliaria',
    'Скорость вентилятора очистителя': "Velocità ventola purificatore",
    'Скорость внешнего вентилятора': "Velocità ventola esterna",
    'Скорость внутреннего вентилятора': "Velocità ventola interna",
    'Верхняя крышка': 'Coperchio superiore',
    'Обнаружена новая верхняя крышка': 'Nuovo coperchio superiore rilevato',
    'Страница управления верхней крышкой доступна на панели управления': 'Pagina controllo coperchio disponibile nel pannello',
    'Нажмите чтобы перейти на страницу управления верхней крышкой': 'Tocca per aprire il controllo coperchio',
    'Нагрев сопла': 'Riscaldamento ugello',
    'нагрев': 'riscald',
    'Нагрев': 'Riscald',
    'Макс. температура платформы': 'Temp. max piano',
    'Макс. температура сопла': 'Temp. max ugello',
    'Мин. температура сопла': 'Temp. min ugello',
    'Аномалия движения по оси': 'Anomalia movimento asse',
    'КранДом Сначала переместите ось Z.': "Tocca prima Home, poi muovi l'asse Z.",
    'Нажмите на пустое поле, чтобы закрыть.': 'Tocca area vuota per chiudere.',
    'Снижение скорости вентилятора может повлиять на качество печати, продолжить?': "Ridurre velocità ventola può influire sulla qualità. Continuare?",
    'В данный момент включен режим внутренней циркуляции, внешний вентилятор не может быть включен': 'Circolazione interna attiva, ventola esterna non disponibile',
    'В данный момент включен режим внешней циркуляции, внутренний вентилятор не может быть включен': 'Circolazione esterna attiva, ventola interna non disponibile',
    'Настройка филамента': 'Configurazione filamento',
    'Автоматическая перезагрузка филамента...': 'Ricarica automatica filamento...',
    'Проверка печатных головок...': 'Controllo testine...',
    'Автоматическая загрузка филамента...': 'Caricamento automatico filamento...',
    'Предварительная экструзия...': 'Pre-estrusione...',
    'Автоматическая выгрузка филамента...': 'Scaricamento automatico filamento...',
    'Автоматический выход филамента': 'Espulsione automatica filamento',
    'Регулировка температуры камеры...': 'Regolazione temperatura camera...',
    'Филамент не распознан. Измените настройки, чтобы продолжить печать.': 'Filamento non riconosciuto. Modifica impostazioni per continuare.',
    'Здесь отображается предустановленный тип филамента для данной модели.': 'Tipo filamento preimpostato per questo modello.',
    'Здесь отображается фактически загруженная в соответствующую печатающую головку нить.': 'Filamento attualmente caricato nella testina.',
    'Принтер автоматически сопоставит предустановленный филамент с загруженным филаментом того же типа и наиболее   близкого цвета. Вы также можете настроить соответствие цветов вручную.': 'Abbinamento automatico per tipo e colore. La configurazione manuale è disponibile.',
    'Выберите филамент того же типа, что и предустановленный, для сопоставления.': 'Scegli filamento dello stesso tipo per abbinamento.',
    'Диаметр сопла не соответствует настройкам файла слайсера. Пожалуйста, убедитесь, что установленный диаметр сопла соответствует параметрам слайсера и проверьте, не изменялась ли информация о сопле.': 'Diametro ugello non corrisponde allo slicer. Verificare le impostazioni ugello.',
    'Производитель': 'Produttore',
    'Филамент': 'Filamento',
    'Тип': 'Tipo',
    'Цвет': 'Colore',
    'Руководство по загрузке филамента': 'Guida caricamento filamento',
    'Просмотреть руководство по загрузке филамента >': 'Guida caricamento filamento >',
    'Переключиться на ручную загрузку >': 'Passa a caricamento manuale >',
    'Выгрузка': 'Scaricamento',
    'Загрузка': 'Caricamento',
    'Официальные филаменты': 'Filamenti ufficiali',
    'Филаменты сторонних производителей': 'Filamenti di terze parti',
    'Особенный': 'Speciale',
    'Ручная загрузка': 'Caricamento manuale',
    'Автоматическая загрузка не удалась?': 'Caricamento automatico fallito?',
    'Ручная подача 1. Нажмите кнопку бокового подающего механизма, чтобы вручную подать нить в подающее отверстие   печатающей головки. 2. Вытяните направляющую трубку материала над печатающей головкой и вручную вставьте нить в головку.': 'Carico manuale: 1. Premi il pulsante laterale per inserire il filamento. 2. Estrai il tubo guida e inserisci manualmente.',
    'Нить загружена, но тип не распознан. Устраните проблему сейчас, чтобы обеспечить правильную печать.': 'Filamento caricato ma tipo sconosciuto. Risolvi per garantire stampa corretta.',
    'Пожалуйста, выберите печатающую головку для выгрузки': 'Seleziona testina per scaricamento',
    'Пожалуйста, выберите печатающую головку для ручной загрузки': 'Seleziona testina per caricamento manuale',
    'Пожалуйста, выберите печатающую головку для автоматической загрузки.': 'Seleziona testina per carico automatico.',
    'выгрузка филамента...': 'scaricamento filamento...',
    'Все печатающие головки разгружены. Извлеките филамент вручную.': 'Tutte le testine scaricate. Rimuovere filamento manualmente.',
    'Вы уверены, что хотите выйти из режима выгрузки филамента?': "Uscire dalla modalità di scaricamento filamento?",
    'Хотите выйти из процесса ручной загрузки?': 'Uscire dal caricamento manuale?',
    'Вручную подавайте нить через подающее устройство до тех пор, пока она полностью не войдет в зацепление с приводными шестернями в печатающей головке.': "Inserire manualmente il filamento nell'alimentatore finché si innesta negli ingranaggi.",
    'Убедитесь что нить правильно зафиксирована в приводных шестернях инструментальной головки': 'Verificare che il filamento sia bloccato negli ingranaggi.',
    'Проверьте успешность экструзии из печатающей головки': "Verificare l'estrusione dalla testina",
    'экструзия': 'estrusione',
    'Экструзия из': 'Estrusione da',
    'Экструдированный': 'Estruso',
    'Повторить экструзию': 'Ripeti estrusione',
    'загрузка филамента...': 'caricamento filamento...',
    'Ручная загрузка выполнена успешно': 'Caricamento manuale completato',
    'Ручная загрузка не удалась': 'Caricamento manuale fallito',
    'Автоматическая загрузка прошла успешно': 'Caricamento automatico riuscito',
    'Автоматическая загрузка не удалась': 'Caricamento automatico fallito',
    'Уборка': 'Pulizia',
    'Очистка от старого филамента': 'Pulizia vecchio filamento',
    'Выгрузка прервана...': 'Scaricamento interrotto...',
    'Прерывание ручной загрузки...': 'Interruzione caricamento manuale...',
    'Ошибка при выгрузке филамента!': 'Errore scaricamento filamento!',
    'Предварительная загрузка филамента': 'Pre-caricamento filamento',
    'Установите катушку, как показано, и попробуйте выполнить подачу. Вставьте филамент в подающий механизм до тех пор, пока индикаторы не подтвердят правильную установку. Система подаст филамент в заданное положение. Автоматическая загрузка завершится при запуске печати.': "Installare la bobina come mostrato. Inserire filamento finché gli indicatori confermano. Il sistema porterà in posizione. Il carico termina all'avvio stampa.",
    'Вставьте филамент в соответствующее подающее отверстие, чтобы завершить процедуру предварительной загрузки.': 'Inserire il filamento nel foro di alimentazione per completare il pre-caricamento.',
    'Режим загрузки': "Modalità caricamento",
    'Режим выгрузки': "Modalità scaricamento",
    'Нет филамента': 'Nessun filamento',
    'Загружено': 'Caricato',
    'Требуется ручное вмешательство': 'Intervento manuale richiesto',
    'Во время процесса выгрузки вытяните нить наружу.': "Durante lo scaricamento, estrarre il filamento verso l'esterno.",
    'Для выгрузки гибких филаментов требуется ручное вмешательство.': 'I materiali flessibili richiedono scaricamento manuale.',
    'Выберите печатающую головку требующую ручной загрузки': 'Seleziona la testina che richiede caricamento manuale',
    'Подача филамента': 'Alimentazione filamento',
    'Прерывание автоматической загрузки...': 'Interruzione caricamento automatico...',
    'Хотите выйти из режима автоматической загрузки филамента?': 'Uscire dalla modalità di caricamento automatico?',
    'Подробная информация о филаменте': 'Dettagli filamento',
    'Устройство подачи филамента не работает.': 'Alimentatore filamento non funziona.',
    'Обнаружен неизвестный филамент. Перед загрузкой отредактируйте профиль материала.': 'Filamento sconosciuto. Modifica profilo materiale prima del carico.',
    'Пожалуйста, выберите тип филамента': 'Seleziona tipo filamento',
    'Гибкие расходные материалы не поддерживают автоматическое втягивание.': 'I materiali flessibili non supportano retrazione automatica.',
    'Автоматическая загрузка': 'Caricamento automatico',
    'Если эта функция отключена, автоматическая загрузка будет отключена для соответствующей печатающей головки.': 'Se disabilitato, il caricamento automatico sarà disattivato per la testina corrispondente.',
    'Распознавание филамента': 'Riconoscimento filamento',
    'Редактирование профиля филамента': 'Modifica profilo filamento',
    'загрузка филамента': 'caricamento filamento',
    'Когда текущий филамент заканчивается, принтер автоматически переключается на другую печатающую головку с тем же материалом и цветом, чтобы продолжить печать.': "Quando il filamento finisce, la stampante passa automaticamente a un'altra testina con stesso materiale e colore.",
    'Калибровка устройства': 'Calibrazione dispositivo',
    'Калибровка завершена': 'Calibrazione completata',
    'Калибровка не удалась': 'Calibrazione fallita',
    'Хотите выйти из процесса калибровки?': 'Uscire dalla calibrazione?',
    'Прервать выравнивание': 'Interrompi livellamento',
    'Калибровка смещения нескольких печатающих головок': 'Calibrazione offset testine multiple',
    'Советы по калибровке смещения экструдеров': 'Suggerimenti calibrazione offset estrusori',
    'Компенсация вибрации': 'Compensazione vibrazione',
    'Советы по калибровке виброгасителей': 'Suggerimenti calibrazione ammortizzatori',
    'Прогресс выравнивания': 'Avanzamento livellamento',
    'Советы по калибровке нагревательной платформы': 'Suggerimenti calibrazione piano riscaldato',
    'Предварительный нагрев нагревательного стола...': 'Pre-riscaldamento piano...',
    'Предварительное зондирование нагревательного стола...': 'Pre-probing piano riscaldato...',
    'Сейчас начнётся компенсация вибрации.\nЭто займёт около 5 минут.\n': "La compensazione vibrazione sta per iniziare.\nRichiederà circa 5 minuti.\n",
    'Очистка сопла...': 'Pulizia ugello...',
    'Очистка сопла': 'Pulizia ugello',
    'Очистка сопла 1': 'Pulizia ugello 1',
    'Очистка сопла 2': 'Pulizia ugello 2',
    'Очистка сопла 3': 'Pulizia ugello 3',
    'Очистка сопла 4': 'Pulizia ugello 4',
    'Очистите сопло прилагаемой проволочной щеткой и поддерживайте чистоту в месте стыковки.': 'Pulire ugello con spazzolino metallico e mantenere pulito il punto di aggancio.',
    'Калибровка сопла 1': 'Calibrazione ugello 1',
    'Калибровка сопла 2': 'Calibrazione ugello 2',
    'Калибровка сопла 3': 'Calibrazione ugello 3',
    'Калибровка сопла 4': 'Calibrazione ugello 4',
    'Калибровка системы подавления вибрации на начальном этапе...': 'Calibrazione sistema anti-vibrazione iniziale...',
    'Калибровка компенсации вибрации...': 'Calibrazione compensazione vibrazione...',
    'Вибрация принтера во время этого процесса является нормальным явлением.': 'Le vibrazioni durante questo processo sono normali.',
    'Тест захвата/установки': 'Test aggancio/installazione',
    'Прервать калибровку': 'Interrompi calibrazione',
    'Охлаждение сопла': 'Raffreddamento ugello',
    'Следуйте приведенной ниже инструкции, чтобы установить печатающую головку на место и проверить ее положение.': 'Seguire le istruzioni per reinstallare la testina e verificarne la posizione.',
    'Неисправность': 'Guasto',
    'Ручное выравнивание': 'Livellamento manuale',
    'Далее, следуя инструкциям, отрегулируйте вручную четыре регулировочных колеса, как показано на рисунке.': 'Seguire le istruzioni e regolare manualmente le quattro ruote come mostrato.',
    'Обратитесь к иллюстрации ниже и вручную поверните четыре регулировочных колеса до тех пор, пока их поверхность не   окажется на одном уровне с концами винтов.': 'Ruotare le quattro ruote fino a che la superficie sia al livello delle viti.',
    'Расчет референсной высоты': 'Calcolo altezza di riferimento',
    'Зондирование': 'Probing',
    'Регулировка колес выравнивания': 'Regolazione ruote livellamento',
    'Повторная проверка контрольных точек...': 'Verifica punti di controllo...',
    'Ручное выравнивание выполнено успешно': 'Livellamento manuale completato',
    'Калибровка возврата в исходное положение': 'Calibrazione ritorno in posizione',
    'Вы уверены, что можете выйти из процесса калибровки возврата в исходное положение?': 'Uscire dalla calibrazione ritorno in posizione?',
    'Прерывание калибровки возврата в исходное положение...': 'Interruzione calibrazione ritorno...',
    'Пожалуйста, выполняйте калибровку только под руководством официальной технической поддержки. Неправильная регулировка может привести к сбоям при возврате в исходное положение или смене инструмента.': 'Eseguire la calibrazione solo con supporto ufficiale. Regolazioni errate causano problemi al ritorno in posizione.',
    'Натяните ремень ГРМ': 'Tendere la cinghia',
    'Ослабьте (но не выкручивайте) два показанных винта, повернув их против часовой стрелки примерно на два оборота.': 'Allentare (senza rimuovere) le due viti di circa due giri in senso antiorario.',
    'Переместите механизм смены печатающих головок вручную по указанной траектории примерно два цикла.': 'Spostare manualmente il meccanismo di cambio testine per circa due cicli.',
    'Затяните два винта в указанных местах.': 'Stringere le due viti nelle posizioni indicate.',
    'Расчетное время': 'Tempo stimato',
    'Пожалуйста, натяните ремень ГРМ и попробуйте снова.': 'Tendere la cinghia e riprovare.',
    'Настройка': 'Impostazione',
    'Калибровка не удалась. Пожалуйста, скорректируйте координаты и повторите попытку.': 'Calibrazione fallita. Correggere le coordinate e riprovare.',
    'Следуйте инструкциям, чтобы совместить установочный штифт    1    с гнездом печатающей головки.   2': 'Seguire le istruzioni per allineare il perno 1 con il vano testina. 2',
    'Выполняется калибровка возврата в исходное положение\u2026': 'Calibrazione ritorno in posizione in corso...',
    'Выполняется калибровка координат печатающей головки\u2026': 'Calibrazione coordinate testina in corso...',
    'Нажимайте кнопки ниже, чтобы отрегулировать положение механизма смены печатающих головок до тех пор, пока установочный штифт не окажется по центру гнезда печатающей головки. После выравнивания нажмите «Avanti': "Usare i pulsanti per regolare il meccanismo finché il perno si centra nel vano testina. Dopo l'allineamento premere Avanti",
    'Корректировку координат следует проводить под руководством специалистов технической поддержки. Произвольные   корректировки могут привести к сбоям в установке/снятии печатающей головки.': 'La correzione coordinate va eseguita con supporto tecnico. Correzioni arbitrarie causano malfunzionamenti.',
    'Нажмите «Fatto': 'Premere Fatto',
    'Регулировка координат при креплении /отсоединении печатающей головки': 'Regolazione coordinate montaggio/smontaggio testina',
    'Выберите печатающую головку, требующую корректировки координат.': 'Seleziona la testina che richiede correzione coordinate.',
    'Настройка координат крепления/отсоединения печатающей головки': 'Impostazione coordinate montaggio/smontaggio testina',
    'Совет: Для точной настройки можно использовать внешний источник света.': 'Suggerimento: usare luce esterna per una regolazione precisa.',
    'Установите печатающую головку обратно на станцию вручную. Затем повторите попытку настройки координат для   установки/снятия.': 'Reinstallare manualmente la testina. Poi ripetere la regolazione coordinate.',
    'Убедитесь, что все печатающие головки надежно закреплены в своих стыковочных станциях.': 'Verificare che tutte le testine siano fissate nelle stazioni.',
    'После завершения установки красная метка на ползунке больше не должна быть видна.': "Dopo l'installazione il segno rosso sul cursore non deve essere visibile.",
    'Вы уверены, что вышли из режима корректировки координат присоединения/отсоединения печатающей головки?': "Uscire dalla modalità di correzione coordinate?",
    'Подтвердить выход? Калибровочные координаты не будут сохранены.': 'Confermare uscita? Le coordinate di calibrazione non saranno salvate.',
    '«Калибровка ручного выравнивания» сейчас\nзапустится, это займет около 10 минут': 'La "Calibrazione Livellamento Manuale" sta per iniziare,\nrichiederà circa 10 minuti.',
    'Снимите PEI-пластину перед калибровкой.': 'Rimuovere la lastra PEI prima della calibrazione.',
    'Перед калибровкой поместите пластину PEI на место.': 'Posizionare la lastra PEI prima della calibrazione.',
    'Выполняется проверка установки PEI-пластины\u2026': 'Verifica installazione lastra PEI...',
    'Определение положения пластины PEI...': 'Rilevamento posizione lastra PEI...',
    'Выравнивание нагреваемой платформы': 'Livellamento piano riscaldato',
    'Калибровка смещения нескольких печатающих головок завершена. Установите PEI-пластину обратно на нагреваемый стол.': 'Calibrazione offset testine completata. Rimettere la lastra PEI sul piano riscaldato.',
    'Обнаружено, что PEI-пластина не снята. Снимите PEI-пластину и нажмите «Avanti': 'Lastra PEI non rimossa. Rimuoverla e premere Avanti',
    'PEI-пластина не обнаружена. Установите PEI-пластину на нагреваемый стол и нажмите «Avanti': 'Lastra PEI non trovata. Installarla sul piano riscaldato e premere Avanti',
    'PEI-пластина не обнаружена. Установите PEI-пластину и нажмите «Avanti': 'Lastra PEI non trovata. Installarla e premere Avanti',
    'Поверните регулировочные колесики, и зеленый ползунок внизу переместится соответствующим образом. Подождите не менее двух   secondi': "Ruotare le ruote di regolazione e il cursore verde si sposterà. Attendere almeno due secondi",
    'Нанесите литиевую смазку': 'Applicare grasso al litio',
    'Нанесите литиевую смазку на 3 стальных шарика на каждой головке': "Applicare grasso al litio sulle 3 sfere d'acciaio di ogni testina",
    'Очистка подпружиненных контактов': 'Pulizia contatti pogo',
    'Очистите контактные штыри на всех печатающих головках и устройстве смены головок с помощью прилагаемой салфетки': 'Pulire i perni di contatto su tutte le testine con il panno in dotazione',
    'Проведение планового технического обслуживания может повлиять на качество печати и срок службы стальных шариков. Подтвердите завершение?': "La manutenzione può influire sulla qualità di stampa. Confermare completamento?",
    'Техническое обслуживание завершено.': 'Manutenzione completata.',
    'Рекомендуется смазка': 'Lubrificazione consigliata',
    'Смазка завершена': 'Lubrificazione completata',
    'Инструкция по замене фильтрующего элемента 1. Откройте крышку фильтра. 2. Извлеките старый фильтр. 3. Установите   новый фильтр. 4. После замены вернитесь на предыдущую страницу и вручную нажмите кнопку «Заменено», чтобы пересчитать время работы фильтра.': 'Sostituzione filtro: 1. Aprire coperchio. 2. Estrarre vecchio filtro. 3. Installare nuovo filtro. 4. Tornare e premere Sostituito per resettare il timer.',
    'Настройки': 'Impostazioni',
    'Сеть': 'Rete',
    'Язык': 'Lingua',
    'Условия предоставления услуг': 'Termini di servizio',
    'Обслуживание': 'Manutenzione',
    'Тайм-аут экрана': 'Timeout schermo',
    'Статистика использования': 'Statistiche utilizzo',
    'Расширенный режим': "Modalità avanzata",
    'Расширенный режим включен': "Modalità avanzata attivata",
    'Отключить расширенный режим': "Disattiva modalità avanzata",
    'Права root': 'Permessi root',
    'Права root включены': 'Permessi root attivati',
    'Права root отключены': 'Permessi root disattivati',
    'Сброс к заводским настройкам': 'Ripristino impostazioni di fabbrica',
    'Подтвердить сброс к заводским настройкам?': 'Confermare ripristino impostazioni di fabbrica?',
    'Восстановление заводских настроек...': 'Ripristino in corso...',
    'Очистить все данные': 'Cancella tutti i dati',
    'Пароль Wi-Fi': 'Password Wi-Fi',
    'Введите SSID сети': 'Inserisci SSID rete',
    'MAC-адрес': 'Indirizzo MAC',
    'Wi-Fi отключен': 'Wi-Fi disattivato',
    'Wi-Fi подключен': 'Wi-Fi connesso',
    'Wi-Fi не подключен': 'Wi-Fi non connesso',
    'Перейдите на страницу настроек Wi-Fi': 'Vai alle impostazioni Wi-Fi',
    'Неверный пароль, пожалуйста, попробуйте еще раз.': 'Password errata, riprovare.',
    'Соединение не удалось, пожалуйста, попробуйте еще раз.': 'Connessione fallita, riprovare.',
    'Сеть управления': 'Rete di controllo',
    'Вы уверены, что хотите удалить эту сеть?': 'Eliminare questa rete?',
    'Подключение к скрытой сети': 'Connessione a rete nascosta',
    'Выберите тип шифрования': 'Seleziona tipo crittografia',
    'Сохраненные сети': 'Reti salvate',
    'Включить максимальную совместимость': "Abilita compatibilità massima",
    'Режим локальной сети': "Modalità rete locale",
    'Локальная сеть': 'Rete locale',
    'Режим локальной сети включен.': "Modalità rete locale attivata.",
    'В режиме локальной сети (LAN) работа служб учетной записи будет прервана.': "In modalità LAN i servizi account saranno interrotti.",
    'Перейти на страницу локальной сети': 'Vai a rete locale',
    'Не удалось установить режим локальной сети.': "Impossibile attivare modalità rete locale.",
    'Не удалось получить информацию о соединении.': 'Impossibile ottenere info connessione.',
    'Не удалось получить код доступа к локальной сети': 'Impossibile ottenere codice rete locale',
    'Код доступа': 'Codice accesso',
    'код доступа': 'codice accesso',
    'Отключить': 'Disconnetti',
    'Отключено': 'Disconnesso',
    'Вы отключаете устройство от клиента в локальной сети? Вы уверены, что отключаете именно его?': 'Disconnettere il dispositivo da un client LAN. Sei sicuro?',
    'Нажатие кнопки отключает это устройство от клиентов локальной сети.': 'Questo disconnette il dispositivo dai client LAN.',
    'К устройству не подключен ни один клиент локальной сети': 'Nessun client LAN connesso al dispositivo',
    'Учетная запись': 'Account',
    'Выбор региона': 'Selezione regione',
    'Материковый Китай': 'Cina continentale',
    'Глобальный': 'Globale',
    'Войти в аккаунт': "Accedi all'account",
    'Подтвердить выход?': 'Confermare uscita?',
    'Имя пользователя': 'Nome utente',
    'Войдите в систему, чтобы включить удаленное управление принтером.': 'Accedere per abilitare il controllo remoto.',
    'Для входа в систему отсканируйте QR-код с помощью приложения Snapmaker.': "Scansiona il QR-code con l'app Snapmaker per accedere.",
    'Перед входом в учетную запись подключитесь к Wi-Fi.': 'Connettiti al Wi-Fi prima di accedere.',
    'Вход с рабочего стола': 'Accesso da desktop',
    'Вход с мобильного устройства': 'Accesso da mobile',
    'ПИН-код': 'PIN',
    'Обновление через': 'Aggiornamento tra',
    'секунд': 'secondi',
    'Нет подключения к интернету. Не удается войти.': 'Nessuna connessione. Impossibile accedere.',
    'Не удалось привязать пользователя': 'Impossibile collegare utente',
    'Получение ПИН-кода...': 'Recupero PIN...',
    'Не удалось получить PIN-код, пожалуйста, проверьте сеть': 'Impossibile ottenere PIN, verificare la rete',
    'Откройте Snapmaker Orca и введите этот codice LAN': 'Aprire Snapmaker Orca e inserire il codice LAN',
    'Проверка сети...': 'Verifica rete...',
    'Проверка устройства...': 'Verifica dispositivo...',
    'Подключение к серверу...': 'Connessione al server...',
    'Отключение от сервера...': 'Disconnessione dal server...',
    'Пожалуйста, подтвердите местоположение устройства и попробуйте снова.': 'Confermare la posizione del dispositivo e riprovare.',
    'Выход из учетной записи не удался.': 'Disconnessione account fallita.',
    'запросить соединение...': 'richiesta connessione...',
    'запрос на подключение не удался': 'richiesta connessione fallita',
    'Использование устройств в разных регионах ограничено; их можно привязать или подключить только в пределах обозначенного региона продаж.': "L'uso in regioni diverse è limitato; il collegamento è possibile solo nella regione di vendita designata.",
    'Текущее устройство находится в недоступном регионе, и сгенерировать QR-код для входа в систему невозможно.': 'Dispositivo in regione non disponibile, impossibile generare QR-code di accesso.',
    'Данное устройство недоступно в регионе, и сгенерировать PIN-код невозможно.': 'Dispositivo non disponibile in questa regione, impossibile generare PIN.',
    'Версия прошивки': 'Versione firmware',
    'Проверяем наличие обновлений...': 'Verifica aggiornamenti...',
    'Уже последняя версия': "Già all'ultima versione",
    'Локальное обновление': 'Aggiornamento locale',
    'Файл обновления не обнаружен': 'File aggiornamento non trovato',
    'Скачать сейчас': 'Scarica ora',
    'Обновите сейчас': 'Aggiorna ora',
    'Проверьте сеть и повторите попытку': 'Controlla la rete e riprova',
    'Нет подключения к интернету. Невозможно обновить онлайн.': 'Nessuna connessione. Aggiornamento online non possibile.',
    'Подтвердите обновление файла': 'Conferma aggiornamento file',
    'Обнаружена новая версия': 'Nuova versione rilevata',
    'Найдена версия': 'Versione trovata',
    'Во время обновления система может перезагрузиться. Не выключайте питание!': "Durante l'aggiornamento il sistema potrebbe riavviarsi. Non spegnere!",
    'Скачать сейчас?': 'Scaricare ora?',
    'Новая версия готова': 'Nuova versione pronta',
    'Обновление займет около 5 minuti': "L'aggiornamento richiederà circa 5 minuti",
    'Обновление займет около 5 минут. Устройство автоматически перезагрузится. Убедитесь, что питание   подключено. Обновить сейчас?': "Aggiornamento in 5 min. Il sistema si riavvierà. Alimentazione collegata? Aggiornare ora?",
    'Обновление прошивки не удалось. Пожалуйста, перезагрузите устройство.': 'Aggiornamento firmware fallito. Riavviare il dispositivo.',
    'Обновление прошивки не удалось. Пожалуйста, проверьте, действителен ли файл прошивки.': "Aggiornamento firmware fallito. Verificare validità del file.",
    '. Устройство автоматически перезагрузится. Убедитесь, что питание   подключено. Обновить сейчас?': ". Il dispositivo si riavvierà. Alimentazione collegata? Aggiornare ora?",
    'Название устройства': 'Nome dispositivo',
    'Модель устройства': 'Modello dispositivo',
    'Серийный номер': 'Numero seriale',
    'Емкость хранилища': "Capacità storage",
    'Системный журнал': 'Log di sistema',
    'Сертификаты': 'Certificati',
    'Обнаружен модуль CAN': 'Modulo CAN rilevato',
    'Модуль CAN не обнаружен': 'Modulo CAN non rilevato',
    'Экспорт фотографий мониторинга ИИ': 'Esporta foto monitoraggio AI',
    'Помогает устранять неполадки в мониторинге ИИ и другие проблемы.': 'Aiuta a risolvere problemi nel monitoraggio AI.',
    'Экспорт журналов в локальное хранилище': 'Esporta log in archivio locale',
    'Журналы экспорта': 'Esporta log',
    'Экспорт... Пожалуйста, подождите.': 'Esportazione... Attendere.',
    'Успешный экспорт': 'Esportazione riuscita',
    'Экспорт не удался. Повторите попытку.': 'Esportazione fallita. Riprovare.',
    'Удаление... Пожалуйста, подождите.': 'Eliminazione... Attendere.',
    'Мониторинг с помощью ИИ': 'Monitoraggio AI',
    'Настройки чувствительности обнаружения': "Sensibilità rilevamento",
    'Обнаружение посторонних предметов': 'Rilevamento oggetti estranei',
    'Принтер автоматически приостановит работу, если во время подготовки будет обнаружен посторонний предмет.': "La stampante si fermerà se viene rilevato un oggetto estraneo.",
    'Идет печать. Нужно ли отключать мониторинг с помощью ИИ?': 'Stampa in corso. Disattivare monitoraggio AI?',
    'Мониторинг с помощью ИИ включен. Выключение светодиода может снизить точность обнаружения. Выключить его все равно?': 'Monitoraggio AI attivo. Spegnere il LED riduce l\'accuratezza. Spegnere comunque?',
    'Ложная тревога обратной связи': 'Segnala falso allarme',
    'Обнаружение печати в воздухе': 'Rilevamento spaghetti',
    'Обнаружение "спагетти"': 'Rilevamento "spaghetti"',
    'Печать автоматически приостанавливается при обнаружении запутывания филамента или засорения сопла.': 'La stampa si ferma se viene rilevato groviglio o ostruzione ugello.',
    'Чувствительность обнаружения печати в воздухе': "Sensibilità rilevamento spaghetti",
    'Обнаружение наматывания': 'Rilevamento aggrovigliamento',
    'Никаких отклонений обнаружено не было;\nобнаружение ИИ было подтверждено как ложная тревога.': 'Nessuna anomalia rilevata;\nmonitoraggio AI confermato come falso allarme.',
    'минут': 'minuti',
    'Никогда': 'Mai',
    'Общее время печати': 'Ore di stampa totali',
    'Количество смен печатающих головок': 'Conteggio cambi testina',
    'Время работы очистителя воздуха': 'Ore filtro aria',
    'Предложите изменения': 'Suggerisci modifiche',
    'Время работы фильтра': 'Vita filtro HEPA',
    'Фильтр работает слишком долго, рекомендуется его заменить.': 'Filtro esausto, si consiglia la sostituzione.',
    'Измененный': 'Modificato',
    'Выполнить смену': 'Esegui sostituzione',
    'Помощник устройства': 'Assistente dispositivo',
    'Новых сообщений нет. Все системы работают в норме.': 'Nessun avviso. Tutti i sistemi operativi.',
    'Код': 'Codice',
    'Напомни мне позже': 'Ricordamelo dopo',
    'Устранение неполадок сейчас': 'Risolvi ora',
    'Код ошибки': 'Codice errore',
    'Посмотреть решение': 'Vedi soluzione',
    '[Ошибка]': '[Errore]',
    '[Предупреждение]': '[Avviso]',
    '[Уведомление]': '[Notifica]',
    'Свяжитесь support@snapmaker.com.': 'Contatta support@snapmaker.com.',
    'Свяжитесь support@snapmaker.com, если проблема сохраняется.': 'Contatta support@snapmaker.com se il problema persiste.',
    'Отсканируйте этот QR-код, чтобы получить руководство по устранению неполадок.': 'Scansiona il QR-code per la guida alla risoluzione dei problemi.',
    'Тестирование устройства': 'Test diagnostici',
    'Камера': 'Telecamera',
    'Очиститель не обнаружен': 'Purificatore non rilevato',
    'Проверка очистителя...': 'Verifica purificatore...',
    'Ошибка очистителя': 'Errore purificatore',
    'Очиститель обычный': 'Purificatore normale',
    'Камера подключена': 'Telecamera connessa',
    'Камера отключена': 'Telecamera disconnessa',
    'Плохо': 'Scarso',
    'Хорошо': 'Bene',
    'Отлично': 'Ottimo',
    'Условия': 'Termini',
    'Для продолжения ознакомьтесь со следующими Условиями и примите их.\n\nУсловия использования\nПолитика конфиденциальности\n': "Per continuare accettare i seguenti Termini.\n\nTermini d'uso\nPrivacy Policy\n",
    'Отсканируйте, чтобы просмотреть полные условия': 'Scansiona per EULA completa',
    'Принтер выполнит следующие калибровки:': "La stampante eseguirà le calibrazioni:",
    'Далее процедура загрузки филамента будет завершена примерно через 5 минут': "Il caricamento filamento si completerà in circa 5 minuti",
    'Не удалось запустить систему_Печатающая головка не обнаружена. Обратитесь в службу технической поддержки.': 'Errore avvio sistema_Testina non rilevata. Contattare il supporto.',
    'Аномалия датчика_Конфигурация датчика АЦП превысила допустимый предел. Система отключена в целях безопасности. Экспортируйте журналы принтера и обратитесь в службу технической поддержки.': 'Anomalia sensore_Configurazione ADC fuori limite. Sistema spento per sicurezza. Esportare log e contattare supporto.',
    'Аномалия температуры сопла_Выключите принтер и проверьте подключение керамического нагревателя или терморезистора печатающей головки 1.': 'Anomalia temp. ugello_Spegnere e verificare riscaldatore/termistore testina 1.',
    'Аномалия температуры сопла_Выключите принтер и проверьте подключение керамического нагревателя или терморезистора печатающей головки 2.': 'Anomalia temp. ugello_Spegnere e verificare riscaldatore/termistore testina 2.',
    'Аномалия температуры сопла_Выключите принтер и проверьте подключение керамического нагревателя или терморезистора печатающей головки 3.': 'Anomalia temp. ugello_Spegnere e verificare riscaldatore/termistore testina 3.',
    'Аномалия температуры сопла_Выключите принтер и проверьте подключение керамического нагревателя или терморезистора печатающей головки 4.': 'Anomalia temp. ugello_Spegnere e verificare riscaldatore/termistore testina 4.',
    'Техническое обслуживание печатной головки_Количество смен печатающих головок достигло значения, требуемого для технического обслуживания. Очистите подпружиненные контакты с обеих сторон и нанесите смазку на стальные шарики и штифты печатающей головки.': 'Manutenzione testina_Cambi raggiunti. Pulire contatti pogo e lubrificare sfere e perni testina.',
    'Блокировка экструзии_Заблокирована экструзия филамента на приводном колесе печатающей головки 1. Проверьте и очистите, затем повторите попытку. Если принтер печатает, нажмите кнопку воспроизведения, чтобы возобновить задание печати.': 'Blocco estrusione_Bloccata ruota testina 1. Verificare e pulire. Se in stampa, premere play per riprendere.',
    'Блокировка экструзии_Заблокирована экструзия филамента на приводном колесе печатающей головки 2. Проверьте и очистите, затем повторите попытку. Если принтер печатает, нажмите кнопку воспроизведения, чтобы возобновить задание печати.': 'Blocco estrusione_Bloccata ruota testina 2. Verificare e pulire. Se in stampa, premere play per riprendere.',
    'Блокировка экструзии_Заблокирована экструзия филамента на приводном колесе печатающей головки 3. Проверьте и очистите, затем повторите попытку. Если принтер печатает, нажмите кнопку воспроизведения, чтобы возобновить задание печати.': 'Blocco estrusione_Bloccata ruota testina 3. Verificare e pulire. Se in stampa, premere play per riprendere.',
    'Блокировка экструзии_Заблокирована экструзия филамента на приводном колесе печатающей головки 4. Проверьте и очистите, затем повторите попытку. Если принтер печатает, нажмите кнопку воспроизведения, чтобы возобновить задание печати.': 'Blocco estrusione_Bloccata ruota testina 4. Verificare e pulire. Se in stampa, premere play per riprendere.',
    'Аномальная температура нагрева печатного стола_Аномалия нагрева печатного стола. Обратитесь в службу технической поддержки.': 'Anomalia riscaldamento piano_Anomalia rilevata. Contattare il supporto.',
    'Аномалия возврата в исходное положение_Текущая печатающая головка недоступна, невозможно выполнить калибровку. Перезапустите принтер и повторите попытку. Если проблема сохраняется, обратитесь в службу технической поддержки.': 'Anomalia homing_Testina non disponibile. Riavviare e riprovare. Se persiste, contattare supporto.',
    'Аномалия обнаружения печатного стола_Обнаружена аномалия в работе нагревательного стола. Обратитесь в службу технической поддержки.': 'Anomalia piano riscaldato_Anomalia rilevata. Contattare il supporto.',
    'Системная аномалия_Печать не возобновилась после отключения электроэнергии.': 'Anomalia sistema_Stampa non ripresa dopo interruzione alimentazione.',
    'Аномалия возврата в исходное положение_Датчик возврата в исходное положение не сработал. Проверьте сопло на наличие остатков нити и очистите его перед повторной попыткой. Если проблема сохраняется, обратитесь в службу технической поддержки.': 'Anomalia homing_Sensore homing non attivato. Controllare e pulire ugello. Se persiste, contattare supporto.',
    'Системная аномалия_Загрузка файла в облачное хранилище не удалась. Проверьте подключение к сети и повторите попытку. Если проблема сохраняется, обратитесь в службу технической поддержки.': 'Anomalia система_Upload file cloud fallito. Verificare rete. Se persiste, contattare supporto.',
    'Аномалия экструзии_Сбой подачи в подающем механизме 1. Возможно, филамент запутался, застрял в экструзионных шестернях или засорилось сопло. Устраните проблему и повторите попытку.': 'Anomalia estrusione_Errore alimentatore 1. Filamento aggrovigliato, bloccato o ugello intasato. Risolvere e riprovare.',
    'Аномалия замены печатной головки_Печатающая головка 1 отсоединена. Установите её обратно вручную, затем нажмите для возобновления задания. Если ошибка не устранена, обратитесь в техническую поддержку.': 'Anomalia cambio testina_Testina 1 scollegata. Reinstallare e premere per riprendere. Se persiste, contattare supporto.',
    'Нераспознанные команды G-кода_Файл для печати содержит команды G-кода, не поддерживаемые данным устройством. Печать прекращена.': 'Comandi G-code non supportati_Il file contiene comandi non supportati. Stampa interrotta.',
    'Сбой калибровки возврата в исходное положение_Пожалуйста, натяните ремень ГРМ и попробуйте снова. Если проблема не исчезнет, выполните калибровку для возврата в исходное положение.': 'Errore cal. homing_Tendere la cinghia e riprovare. Se persiste, eseguire calibrazione homing.',
    'Обнаружена неравномерность нагрева стола_Отклонение плоскостности нагреваемого стола слишком велико. Выполните ручное выравнивание стола.': "Piano irregolare_Planarità fuori tolleranza. Eseguire livellamento manuale.",
    'Сбой калибровки возврата в исходное положение_Ошибка диагонального зондирования.': 'Errore cal. homing_Errore probing diagonale.',
    'Сбой калибровки возврата в исходное положение_Не удалось проверить точку зондирования.': 'Errore cal. homing_Impossibile verificare punto di probing.',
    'Сбой калибровки возврата в исходное положение_Достигнуто максимальное количество попыток.': 'Errore cal. homing_Raggiunto numero massimo tentativi.',
    'Мало места в хранилище_Недостаток памяти на устройстве может повлиять на функциональность печати. Удалите некоторые файлы G-кода или таймлапса, чтобы освободить место.': "Spazio insufficiente_Lo spazio ridotto può influire sulla stampa. Eliminare file Gcode o timelapse.",
    'Аномалия обнаружения_Установите любую одну печатающую головку и повторите попытку.': 'Anomalia rilevamento_Installare almeno una testina e riprovare.',
    'Аномалия обнаружения печатного тола_PEI-пластина установлена неправильно. Установите PEI-пластину корректно и повторите попытку.': 'Anomalia rilevamento piano_Lastra PEI installata in modo errato. Reinstallare correttamente.',
    'Возможно, на печатном столе обнаружен посторонний предмет_Пожалуйста, проверьте и удалите все посторонние предметы. Если посторонних предметов не обнаружено, нажмите «Continua': 'Oggetto estraneo rilevato sul piano_Verificare e rimuovere. Se non trovato, premere Continua',
    'Обнаружен возможный дефект спагетти_Пожалуйста, осмотрите модello. Если обнаруженные дефекты допустимы или дефекты не найдены, нажмите «Continua': 'Possibile difetto spaghetti_Ispezionare il modello. Se accettabile, premere Continua',
    'На печатной платформе обнаружены возможные остатки._Пожалуйста, проверьте и удалите все остатки клея. Если ничего не обнаружено, нажмите «Continua': 'Possibili residui sul piano_Verificare e rimuovere residui di colla. Se assenti, premere Continua',
    '• Специальные разрешения при активации\n  • Включение этой опции предоставляет вам права на\n    изменение файлов конфигурации принтера. Мы\n    настоятельно не рекомендуем изменять эти настройки,\n    если вы полностью не понимаете функции параметров\n    конфигурации принтера. Произвольные изменения\n    могут привести к сбоям в работе функций устройства,\n    таких как защита от перегрева, калибровка XYZ,\n    выравнивание нагреваемого стола и автоматическая\n    подача филамента.\n  • Modalità sviluppatore\n   позволяет свободно добавлять,\n    удалять или изменять файлы конфигурации устройства,\n    что может привести к потенциальным проблемам,\n    включая, помимо прочего: дефекты заданий печати,\n    непоправимый ущерб принтеру, необратимый вред,\n    а также проблемы с безопасностью и\n    конфиденциальностью данных.\n• Влияние на права и интересы послепродажного\n    обслуживания\n  • Компания Snapmaker не имеет возможности установить\n    или проверить результаты, вытекающие из активации\n    расширенного режима. Включая этот режим, вы\n    признаете и принимаете все связанные с этим риски\n    или последствия и берете на себя полную\n    ответственность за них. В максимальной степени,\n    допустимой действующим законодательством, мы не\n    несем ответственности за любые убытки или риски,\n    возникающие в результате использования или\n    невозможности использования продукта, а также не\n    обязуемся предоставлять техническую поддержку\n    по вопросам или аномалиям, возникающим во время\n    использования продукта, включая, помимо прочего,\n    сбои в работе системы, невозможность выполнения\n    команд или потерю файлов.': "• Permessi speciali all'attivazione\n  • Questa opzione concede i diritti di modifica dei file di configurazione. Si sconsiglia vivamente di modificare queste impostazioni senza conoscerle. Modifiche arbitrarie possono causare guasti come protezione da surriscaldamento, calibrazione XYZ, livellamento piano e alimentazione filamento.\n  • La modalita' avanzata consente di modificare liberamente i file di configurazione, il che puo' causare difetti di stampa, danni irreparabili, problemi di sicurezza e privacy.\n• Impatto sulla garanzia post-vendita\n  • Snapmaker non puo' stabilire o verificare i risultati derivanti dall'attivazione della modalita' avanzata. Attivando questa modalita', si riconoscono e si accettano tutti i rischi. Nella misura massima consentita dalla legge, non siamo responsabili per perdite o rischi derivanti dall'uso del prodotto."
}

def patch_binary(src, dst, translations):
    if not os.path.exists(src):
        print(f"[-] Errore: File {src} non trovato!")
        sys.exit(1)

    if not os.path.exists(BAK):
        print(f"[*] Creazione backup in {BAK}...")
        os.system(f"cp {src} {BAK}")

    with open(src, 'rb') as f:
        data = bytearray(f.read())

    items = sorted(translations.items(), key=lambda x: len(x[0].encode('utf-8')), reverse=True)

    ok = skip = notfound = 0
    print("[*] Iniezione traduzioni in corso...")

    for ru_str, it_str in items:
        ru_b = ru_str.encode('utf-8')
        it_b = it_str.encode('utf-8')
        
        if len(it_b) > len(ru_b):
            skip += 1
            continue
            
        padded_it = it_b + b'\x00' * (len(ru_b) - len(it_b))
        
        count = idx = 0
        while True:
            pos = data.find(ru_b, idx)
            if pos == -1: break
            data[pos:pos+len(ru_b)] = padded_it
            idx = pos + len(padded_it)
            count += 1
            
        if count > 0: ok += 1
        else: notfound += 1

    orig_debug = b'/oem/.debug'
    fake_debug = b'/oem/.dummy'
    idx = 0
    while True:
        pos = data.find(orig_debug, idx)
        if pos == -1: break
        data[pos:pos+len(orig_debug)] = fake_debug
        idx = pos + len(fake_debug)

    with open(dst, 'wb') as f:
        f.write(data)

if __name__ == '__main__':
    patch_binary(SRC, DST, TRANSLATIONS)
    print("\n[*] Installazione di sistema in corso...")
    os.system("touch /oem/.debug") 
    os.system("killall gui 2>/dev/null")
    os.system(f"rm -f {SRC}")
    os.system(f"cp {DST} {SRC}")
    os.system(f"chmod +x {SRC}")
    os.system("killall gui 2>/dev/null")
    print("\n[V] FATTO! L'interfaccia si sta riavviando in Italiano.")
